language: php

php:
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - cp ruleset.xml.dist ruleset.xml

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpcs --standard=ruleset.xml src/
