language: php

php:
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install
  - cp ruleset.xml.dist ruleset.xml

script:
  - php vendor/bin/phpunit
  - php vendor/bin/phpcs --standard=ruleset.xml src/
